image: Visual Studio 2017
platform: x64
build: off

environment:
  global:
    CONDA: C:\Miniconda36-x64
    MPLBACKEND: Agg

  matrix:
    - PYTHON_VERSION: "3.5"
      TORCH_VERSION: "0.4.0"

    - PYTHON_VERSION: "3.5"
      TORCH_VERSION: "0.4.1"

    - PYTHON_VERSION: "3.5"
      TORCH_VERSION: "1.0.0"

    - PYTHON_VERSION: "3.6"
      TORCH_VERSION: "0.4.0"

    - PYTHON_VERSION: "3.6"
      TORCH_VERSION: "0.4.1"

    - PYTHON_VERSION: "3.6"
      TORCH_VERSION: "1.0.0"

    - PYTHON_VERSION: "3.7"
      TORCH_VERSION: "0.4.1"

    - PYTHON_VERSION: "3.7"
      TORCH_VERSION: "1.0.0"

init:
  - "ECHO %PYTHON_VERSION% %TORCH_VERSION%"
  - "set PATH=%CONDA%;%CONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda info -a
  - "conda create -n build_env python=%PYTHON_VERSION%"
  - activate build_env
  - conda install cython
  - conda install -c conda-forge suitesparse
  - python --version

install:
  - "conda install -c pytorch pytorch-cpu=%TORCH_VERSION%"
  - pip install torchvision
  - pip install ecos==2.0.7rc1
  - pip install -e ".[test]"

test_script:
  - python -m unittest
