language: python

matrix:
  include:
    - os: linux
      python: 3.5
      env: TORCH_WHL=http://download.pytorch.org/whl/cpu/torch-0.4.0-cp35-cp35m-linux_x86_64.whl

    - os: linux
      python: 3.5
      env: TORCH_WHL=http://download.pytorch.org/whl/cpu/torch-0.4.1-cp35-cp35m-linux_x86_64.whl

    - os: linux
      python: 3.6
      env: TORCH_WHL=http://download.pytorch.org/whl/cpu/torch-0.4.0-cp36-cp36m-linux_x86_64.whl

    - os: linux
      python: 3.6
      env: TORCH_WHL=http://download.pytorch.org/whl/cpu/torch-0.4.1-cp36-cp36m-linux_x86_64.whl

    - os: linux
      dist: xenial
      sudo: true
      python: 3.7
      env:
        - TORCH_WHL=http://download.pytorch.org/whl/cpu/torch-0.4.1.post2-cp37-cp37m-linux_x86_64.whl
        - CVXOPT_SUITESPARSE_SRC_DIR=/home/travis/SuiteSparse
      before_install:
        - sudo apt-get update -y
        - sudo apt-get install -y libblas-dev liblapack-dev
        - wget http://faculty.cse.tamu.edu/davis/SuiteSparse/SuiteSparse-5.3.0.tar.gz
        - tar xf SuiteSparse-5.3.0.tar.gz -C /home/travis

install:
  - pip install $TORCH_WHL
  - pip install "tqdm>=4.0"
  - pip install "cvxpy>=0.4,<1.0"
  - pip install cvxopt

script:
  - python -m unittest
