os:
  - linux
  - osx

language: generic

env:
  - PYTHON_VERSION=3.5
  - PYTHON_VERSION=3.6
  - PYTHON_VERSION=3.7

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      CONDA_DOWNLOAD="https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh";
      PYTORCH="pytorch";
    else
      CONDA_DOWNLOAD="https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh";
      PYTORCH="pytorch-cpu";
    fi
  - wget $CONDA_DOWNLOAD -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda info -a

install:
  - conda create -n build_env python=$PYTHON_VERSION
  - source activate build_env
  - conda install -c pytorch $PYTORCH
  - pip install -e ".[test]"

script:
  - python --version
  - python -m unittest --failfast
