os:
  - linux
  - osx

language: generic

cache:
  directories:
    - $HOME/.cache/pip/
    - $HOME/miniconda/pkgs/

env:
  - PYTHON_VERSION=3.5
  - PYTHON_VERSION=3.6
  - PYTHON_VERSION=3.7

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      CONDA_DOWNLOAD="https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh";
      PYTORCH="pytorch";
    else
      CONDA_DOWNLOAD="https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh";
      PYTORCH="pytorch-cpu";
    fi
  - wget $CONDA_DOWNLOAD -O $HOME/miniconda.sh
  - bash $HOME/miniconda.sh -b -u -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no

install:
  - conda create -n build_env python=$PYTHON_VERSION
  - source activate build_env
  - conda install -c pytorch $PYTORCH
  - pip install tqdm scipy cvxpy cvxopt

before_script:
  - conda list
  - python --version
  - pip freeze

script:
  - python -m unittest --failfast
