name: Test package

on:
  push:
    branches:
    - master
    paths:
    - 'gel/*'
    - 'tests/*'
    - '.github/workflows/test-package.yml'
    - 'pyproject.toml'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]
      fail-fast: false

    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    - uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install poetry
      run: python -m pip install poetry
    - name: Install dependencies
      run: |
        python -m poetry install --no-dev -E 'test'
        python -m pip install torch
    - name: Run tests
      run: python -m unittest
